name: C/C++ CI

env:
  LD_LIBRARY_PATH: ${{ github.workspace }}/lib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make test
      run: make test
