name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "$env:/lib/" >> $env:GITHUB_PATH
    - name: make
      run: make
    - name: setup environment variable for dynamic library
      run: echo '::set-env name=LD_LIBRARY_PATH::/lib/'
    - name: make test
      run: make test
