name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "/home/runner/work/_temp/data_structure_lib/lib/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: make
      run: make
    - name: setup environment variable for dynamic library
      run: echo '::set-env name=LD_LIBRARY_PATH::/lib/'
    - name: make test
      run: make test
