name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "/home/runner/work/data_structure_lib/data_structure_lib/lib/" >> $GITHUB_PATH
    - name: make
      run: make
    - name: make test
      run: make test
