name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: echo "$((Get-Item .).FullName)/lib/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: make
      run: make
    - name: make test
      run: make test
